[package]
name = "dbfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jammdb = {path = "../jammdb"}
fat32-trait = {path = "../fs/fat32-trait"}


logger = {path="../logger"}